### ISSUE TITLE
Last update error

### ISSUE THREAD

**Issue by sborys-ai** [bmad4ever/ComfyUI-Bmad-DirtyUndoRedo#5]
Update custom node 'ComfyUI-Bmad-DirtyUndoRedo'
Update: ['https://github.com/bmad4ever/ComfyUI-Bmad-DirtyUndoRedo']
Update(git-clone) error: https://github.com/bmad4ever/ComfyUI-Bmad-DirtyUndoRedo / Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v --rebase -- origin
  stderr: 'error: The following untracked working tree files would be overwritten by merge:'

**Comment by bmad4ever** [comment]
Hello,

That is not a problem with this repository, but rather w/ your local setup.
Looking at the error, it appears there are untracked files, possibly copied/downloaded without using git.
I can not identify the origin of the problem, but if you delete the folder and clone the repo anew it should work fine.

If you are using the manager, uninstalling and reinstalling should also do the trick.
However, if that does not work, then you will have to do it manually:
1. Navigate to `/ComfyUI/custom_nodes/` folder;
2. Delete the ComfyUI-Bmad-DirtyUndoRedo folder;
3. Run `git clone https://github.com/bmad4ever/ComfyUI-Bmad-DirtyUndoRedo`.

Best Regards

**Comment by sborys-ai** [comment]
Thank you, the reinstallation helped!

**Comment by picobyte** [comment]
It could also be the byte compiled python file sin the __pycache__ directory, then #6 should fix this.
