### ISSUE TITLE
cannot copy/paste a node after installing

### ISSUE THREAD

**Issue by screan** [bmad4ever/ComfyUI-Bmad-DirtyUndoRedo#8]
There is an issue after installing. you cannot copy/paste a node after installing. 

Found this solution to remove DirtyundoRedo if you have this issue. 

Remove it from your custom modes and from web/extensions folders

https://www.reddit.com/r/comfyui/comments/15k21e5/copypaste_nodes_is_glitching_my_ui_and_i_can_only/

**Comment by bmad4ever** [comment]
The latest commit should have fixed this problem; however, if it continues on your end, or some other problem arises from the fix, please report back.

I will close the issue next week if no additional complaints about this behavior arise.

Kind Regards.

**Comment by screan** [comment]
Working!
