### ISSUE TITLE
How to continue using this plugin,the official undo usage is poor

### ISSUE THREAD

**Issue by cheezmil** [bmad4ever/ComfyUI-Bmad-DirtyUndoRedo#9]
The official undo is too torturous. Ctrl+Z has not responded at all. Even the selection has been marked as a revocation step, and it seems to conflict with Efficientnode. I don't know why, but I used this plugin well before

According to what you said, "Optionally, if you wish to keep using the extension, you will have to remove the undoRedo. js from the web \ extensions \ core directory."

“

I found that there is still the same reaction as the official undo

In addition, when the official undo button presses Ctrl+Z, the preview image always disappears, which is very troublesome. It would be great if this problem could be solved

**Comment by bmad4ever** [comment]
Hi,

I have to address your issue with some additional questions.
**You mentioned the official is 'too torturous', did you disable this extension and delete the ZZZ-Bmad-DirtyUndoRedo folder prior to using it?** 

If so, and you prefer this extension behavior, but it seems broken now, my first guess is that one of the following (or both) apply:
1. You are updating Comfy and "undoRedo.js" is placed within the folder again, conflicting with this extension.
2. I've updated this extension near the time the official undo was added, and I might have broken some previously working behavior.

I doubt I can address any of these soon, but, with respect to potential problem number 2, I would need to better understand the problems you mentioned.
**Can you elaborate more (ignoring the last point about the previews)?
From what extension is the Efficient node (or is that the name of the extension???), what is the current and the desired behavior, etc...**


Depending on the nature of the problem:
1. I could try to bypass (or delete) the undoRedo.js when the extension is active. Preferably, bypass; deleting could lead to confusion when disabling this extension.
2. I would have to verify older versions of this extension to check when it stopped behaving correctly and why.


Best Regards



P.S. have you communicated the problem(s) pertaining to the official undo in the official Comfy repo or to pythongosssss? It may be the case that the problems you mentioned are easy to solve but the devs aren't aware of them.

**Comment by cheezmil** [comment]
"You mentioned the official is 'too torturous', did you disable this extension and delete the ZZZ-Bmad-DirtyUndoRedo folder prior to using it?"
YES.  I deleted the ZZZ Mamad DirtyUndoRedo folder and used the official one.

"You are updating Comfy and "undoRedo.js" is placed within the folder again, conflicting with this extension."
NO.  UnderRedo.js has been deleted by me.

"From what extension is the Efficient node (or is that the name of the extension???), what is the current and the desired behavior, etc..."
Using the official undo, pressing ctrl+z inexplicably elongates the length of the Efficient Loader, but I have not done anything with it I remember using your plugin before wouldn't have caused this situation.

"P.S. have you communicated the problem(s) pertaining to the official undo in the official Comfy repo or to pythongosssss? It may be the case that the problems you mentioned are easy to solve but the devs aren't aware of them."
YES..They didn't reply

"I've updated this extension near the time the official undo was added, and I might have broken some previously working behavior."
It should be like this. After I updated comfyui and all the plugins, there was an issue just like now.

Thank you for your reply!

**Comment by cheezmil** [comment]
Whenever ctrl+z is pressed, the preview image disappears, and this problem persists. Whether it is ZZZ Mamad DirtyUndoRedo or official undo, this problem occurs. Is there a way to solve this problem, as preview images can provide reference in some workflows


I don't want to use official undo because when I select a node, it will be marked as a step, which is too annoying. Ctrl+z will cancel the selection But in fact, this node should be restored. Previously, using your plugin did not cause this problem But now the plugin doesn't work anymore

**Comment by cheezmil** [comment]
A few days ago, the official resolved the issue of the preview image disappearing
